# config/geo_map.py
# Geo-entity → region lookup and military keyword list.
# Edit this file to tune classification — no logic files need changing.

REGION_GEO_MAP = {
    # --- middle_east ---
    "iran": "middle_east", "iraq": "middle_east", "saudi arabia": "middle_east",
    "saudi": "middle_east", "israel": "middle_east", "gaza": "middle_east",
    "west bank": "middle_east", "lebanon": "middle_east", "syria": "middle_east",
    "jordan": "middle_east", "egypt": "middle_east", "turkey": "middle_east",
    "uae": "middle_east", "emirates": "middle_east", "qatar": "middle_east",
    "kuwait": "middle_east", "bahrain": "middle_east", "oman": "middle_east",
    "yemen": "middle_east", "houthi": "middle_east", "riyadh": "middle_east",
    "tehran": "middle_east", "tel aviv": "middle_east", "jerusalem": "middle_east",
    "beirut": "middle_east", "damascus": "middle_east", "baghdad": "middle_east",
    "cairo": "middle_east", "ankara": "middle_east", "doha": "middle_east",
    "abu dhabi": "middle_east", "dubai": "middle_east", "persian gulf": "middle_east",
    "strait of hormuz": "middle_east", "hezbollah": "middle_east", "hamas": "middle_east",
    "irgc": "middle_east", "mosul": "middle_east", "aleppo": "middle_east",
    "idlib": "middle_east", "raqqa": "middle_east", "sinai": "middle_east",
    "suez": "middle_east", "opec": "middle_east", "libyan": "middle_east",
    "tripoli": "middle_east",

    # --- europe ---
    "ukraine": "europe", "russia": "europe", "germany": "europe", "france": "europe",
    "united kingdom": "europe", "britain": "europe", "england": "europe",
    "poland": "europe", "romania": "europe", "moldova": "europe", "belarus": "europe",
    "georgia": "europe", "armenia": "europe", "azerbaijan": "europe",
    "serbia": "europe", "croatia": "europe", "spain": "europe", "italy": "europe",
    "greece": "europe", "hungary": "europe", "sweden": "europe", "finland": "europe",
    "norway": "europe", "denmark": "europe", "netherlands": "europe",
    "belgium": "europe", "austria": "europe", "czech": "europe", "slovakia": "europe",
    "switzerland": "europe", "albania": "europe", "montenegro": "europe",
    "north macedonia": "europe", "bosnia": "europe", "kosovo": "europe",
    "kyiv": "europe", "moscow": "europe", "berlin": "europe", "paris": "europe",
    "london": "europe", "rome": "europe", "madrid": "europe", "stockholm": "europe",
    "warsaw": "europe", "brussels": "europe", "lisbon": "europe", "amsterdam": "europe",
    "vienna": "europe", "prague": "europe", "bucharest": "europe", "budapest": "europe",
    "oslo": "europe", "helsinki": "europe", "tallinn": "europe", "riga": "europe",
    "vilnius": "europe", "minsk": "europe", "baku": "europe", "yerevan": "europe",
    "tbilisi": "europe", "european union": "europe", "eurozone": "europe",
    "nato": "europe", "kremlin": "europe", "donbas": "europe", "donbass": "europe",
    "luhansk": "europe", "donetsk": "europe", "kharkiv": "europe", "odesa": "europe",
    "mariupol": "europe", "zaporizhzhia": "europe", "crimea": "europe",
    "nordstream": "europe", "nord stream": "europe", "schengen": "europe",
    "brexit": "europe", "ecb": "europe", "european": "europe",

    # --- apac ---
    "china": "apac", "japan": "apac", "north korea": "apac", "south korea": "apac",
    "taiwan": "apac", "australia": "apac", "new zealand": "apac",
    "hong kong": "apac", "macau": "apac", "mongolia": "apac",
    "beijing": "apac", "tokyo": "apac", "seoul": "apac", "canberra": "apac",
    "auckland": "apac", "taipei": "apac", "pyongyang": "apac", "ulaanbaatar": "apac",
    "xi jinping": "apac", "prc": "apac", "pla": "apac", "east china sea": "apac",
    "yellow sea": "apac", "sea of japan": "apac", "south china sea": "apac",
    "rare earth": "apac", "semiconductor": "apac",

    # --- se_asia ---
    "indonesia": "se_asia", "malaysia": "se_asia", "philippines": "se_asia",
    "thailand": "se_asia", "vietnam": "se_asia", "singapore": "se_asia",
    "myanmar": "se_asia", "cambodia": "se_asia", "laos": "se_asia",
    "brunei": "se_asia", "timor": "se_asia", "asean": "se_asia",
    "jakarta": "se_asia", "kuala lumpur": "se_asia", "manila": "se_asia",
    "bangkok": "se_asia", "hanoi": "se_asia", "ho chi minh": "se_asia",
    "naypyidaw": "se_asia", "yangon": "se_asia", "rangoon": "se_asia",
    "phnom penh": "se_asia", "vientiane": "se_asia", "rohingya": "se_asia",
    "strait of malacca": "se_asia",

    # --- s_asia ---
    "india": "s_asia", "pakistan": "s_asia", "bangladesh": "s_asia",
    "sri lanka": "s_asia", "nepal": "s_asia", "bhutan": "s_asia",
    "afghanistan": "s_asia", "maldives": "s_asia",
    "new delhi": "s_asia", "islamabad": "s_asia", "dhaka": "s_asia",
    "colombo": "s_asia", "kathmandu": "s_asia", "kabul": "s_asia",
    "kashmir": "s_asia", "taliban": "s_asia", "modi": "s_asia",
    "indo-pak": "s_asia", "line of control": "s_asia",

    # --- americas ---
    "united states": "americas", "america": "americas", "canada": "americas",
    "mexico": "americas", "brazil": "americas", "argentina": "americas",
    "colombia": "americas", "venezuela": "americas", "chile": "americas",
    "peru": "americas", "ecuador": "americas", "bolivia": "americas",
    "uruguay": "americas", "paraguay": "americas", "panama": "americas",
    "costa rica": "americas", "cuba": "americas", "haiti": "americas",
    "honduras": "americas", "nicaragua": "americas", "el salvador": "americas",
    "guatemala": "americas", "dominican republic": "americas", "caribbean": "americas",
    "latin america": "americas", "washington": "americas", "ottawa": "americas",
    "mexico city": "americas", "brasilia": "americas", "bogota": "americas",
    "caracas": "americas", "buenos aires": "americas", "santiago": "americas",
    "white house": "americas", "pentagon": "americas",
    "us senate": "americas", "federal reserve": "americas", "wall street": "americas",

    # --- africa ---
    "nigeria": "africa", "ethiopia": "africa", "kenya": "africa", "ghana": "africa",
    "south africa": "africa", "morocco": "africa", "tanzania": "africa",
    "congo": "africa", "angola": "africa", "mozambique": "africa",
    "zimbabwe": "africa", "zambia": "africa", "malawi": "africa",
    "somalia": "africa", "sudan": "africa", "south sudan": "africa",
    "chad": "africa", "mali": "africa", "niger": "africa",
    "burkina faso": "africa", "senegal": "africa", "ivory coast": "africa",
    "cote d'ivoire": "africa", "cameroon": "africa", "rwanda": "africa",
    "burundi": "africa", "uganda": "africa", "djibouti": "africa",
    "eritrea": "africa", "libya": "africa", "tunisia": "africa",
    "algeria": "africa", "abuja": "africa", "addis ababa": "africa",
    "nairobi": "africa", "accra": "africa", "johannesburg": "africa",
    "pretoria": "africa", "dar es salaam": "africa", "kinshasa": "africa",
    "luanda": "africa", "mogadishu": "africa", "khartoum": "africa",
    "bamako": "africa", "niamey": "africa", "ouagadougou": "africa",
    "dakar": "africa", "abidjan": "africa", "sahel": "africa",
    "horn of africa": "africa", "sub-saharan": "africa",
    "al-shabaab": "africa", "boko haram": "africa", "ecowas": "africa",
}

MILITARY_KEYWORDS = [
    "military", "troops", "forces", "soldier", "soldiers", "army", "navy",
    "air force", "marine", "marines", "missile", "missiles", "strike",
    "airstrike", "air strike", "bomb", "bombing", "drone", "drones",
    "warfare", "combat", "warship", "aircraft carrier", "invasion",
    "offensive", "weapon", "weapons", "arsenal", "artillery", "tank",
    "tanks", "battalion", "special forces", "pentagon", "war", "ceasefire",
    "siege", "blockade", "shelling", "casualty", "casualties", "killed in action",
    "defense minister", "defence minister", "joint chiefs", "general", "admiral",
    "deployment", "deployed", "escalation", "nuclear", "ballistic",
    "munitions", "ammunition", "fighter jet", "warplane", "submarine",
    "frigate", "destroyer", "military base", "nato exercise",
]
